### PR TITLE
Added multiple screen orientation support.

### PR DESCRIPTION
**Pull request by JusCezari**
Added multiple screen orientation support using saved states in the view. It was used two new variables, one to hold the savedBitmap to prevent it from making new bitmaps when there wasn't changes (that was making the bitmap smaller at each screen orientation change) and another to flag an edit in the new orientation. I renamed the clear function to clearView to change the edit flag only when the user clicked in the clear button, not just when the old clear function was called (when the screen orientation changes this function is called).
Any suggestions are welcome.

### CODE REVIEW

**Comment by xjiaoyang** [comment]
@JusCezari i think we should work together to make screen rotation working on #58

**Comment by gcacace** [comment]
Currently we should also retain the SVG data structure, otherwise screen rotations will keep only the bitmap. I am doing code refactoring to hold the set of bezier curves, so the signature bitmap can be then rebuilt from the drawn path.

**Comment by dewafer** [comment]
Do you have plan on releasing it?

**Comment by Mauker1** [comment]
Is there a milestone for this?

**Pull request merged**
